import { BaseEditableModel } from "app/shared/models/BaseEditableModel";
import { ClassInfo } from "./ClassInfo";
import { TakerOptions } from "./TakerOptions";

export class Doc extends BaseEditableModel {
    batchId?: string;
    batchReference?: string;
    batchDescription?: string;
    examinationId?: string;
    examinationType?: string;
    examId?: string;
    examDescription?: string;
    examSubjectId?: string;
    examSubjectCode?: string;
    examSubjectName?: string;
    questionSetTypeId?: string;
    questionSetTypeCode?: string;
    questionSetTypeName?: string;
    questionSetId?: string;
    questionSetCode?: string;
    questionSetName?: string;
    status?: string;        // E_RELEASED, E_ON_HOLD, E_CANCELLED    
    remark?: string;
    takerType?: string;
    takerId?: string;
    takerCode?: string;
    takerName?: string;
    takerUsername?: string;
    classInfo?: any;
    classId?: string;
    classCode?: string;
    className?: string;
    resDeadlineType: string;
    resDateFrom?: number;
    resTimeFrom?: string;
    resDateTo?: number;
    resTimeTo?: string;
    submitStatus?: string;
    submitStartAt?: number;
    submitEndAt?: number;
    submitSeconds?: number;
    reviewStatus?: string;  // E_PENDING, E_COMPLETED
    autoReview?: boolean;
    reviewedAt?: number;
    reviewedById?: string;
    reviewedByCode?: string;
    reviewedByName?: string;
    maxScores?: number;
    resultScores?: number;
    questionCount?: number;
    completedCount?: number;
    docItemsStr?: string;
    requestType?: string;
    itemJSON?: string;
    takerOptions?: any;
    retake?: boolean;
    retakeCount?: number;
    retakeNo?: number;
    linkedDocId?: string;
    questionIdList?: string[] = [];
}